import os
import sys
import django

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'App.settings')
django.setup()

from garagem_app.models import Miniatura

nomes = [
    "Land Rover Defender Double Cab",
    "Mazda Miata",
    "Ford Raptor",
    "Ford Raptor Chevy Nova Wagon Chevy Belair",
    "Bat Boat Bateau",
    "Mustang",
    "Brazilian Dodge Charger",
    "Datsun Sunny Truck",
    "Datsun Sunny Truck Dodge Lil Red Express Truck",
    "Porsche",
    "Jeep Wagoneer",
    "Chevy Silverado Trail Boss",
    "Viper",
    "Viper Bentley Continental",
    "Bentley Continental",
    "Honda Civic Type",
    "Ford Mustang Shelby",
    "Koenigsegg Jesko",
    "Koenigsegg Jesko Ram Rebel",
    "Koenigsegg Jesko Mainline",
    "Dodge Charger Hellcat",
    "Jeep Gladiator",
    "Ford Bronco",
    "Ford Maverick Custom",
    "Ram",
    "Chevy Fleetline",
    "Chevy Fleetline Chevy",
    "Chevy",
    "Chevy Impala",
    "Chevy Impala Alarm",
    "Corvette Gasser Full White Rim",
    "Corvette Gasser White Outer Rim",
    "Corvette Gasser",
    "Buick Riviera",
    "Corvette Gas Monkey Garage",
    "Dodge Dart",
    "Lotus Type",
    "Corvette Racer",
    "Dodge Coronet Superbee",
    "Dodge Coronet Superbee Chevy Camaro",
    "Dodge Challenger",
    "Dodge Power Wagon",
    "Dodge Power Wagon Plymouth Superbird",
    "Mustang Funny Car",
    "Mustang Funny Car Jeep",
    "Mustang Funny Car Pontiac Firebird",
    "Pontiac Firebird",
    "Chevy Blazer Custom",
    "Chevy Chevette Chevy Chevette",
    "Chevy Chevette",
    "El Camino",
    "Chevy Silverado",
    "Audi Sport Quattro",
    "Honda City Turbo Purple",
    "Audi Quattro",
    "Buick Regal",
    "Mercedes Benz",
    "Acura",
    "Honda Civic",
    "Honda Civic Loose",
    "Audi Avant",
    "Bugatti",
    "Mazda Drift",
    "Dodge Viper",
    "Dodge Viper O",
    "Ford Lightning",
    "Aint Fare",
    "Alfa Romeo Giulia Ti Super Red",
    "Alfa Romeo Giulia Ti Super Red New For",
    "Alfa Romeo Giulia Ti Super",
    "Alpha Pursuit",
    "Alpha Pursuit Arrow Dynamic",
    "Arrow Dynamic",
    "Aston Martin High Speed Edition",
    "Batman Arkham Asylum Batmobile",
    "Batman Arkham Asylum Batmobile The Batman Batmobile",
    "Batman Robin Batmobile",
    "Batman Robin Batmobile Batman",
    "Batmobile",
    "Batmobile Batmobile Hauler",
    "Big Air Bel Air",
    "Birthday Burner",
    "Csi",
    "Hot Wheels Mainline Variation",
    "Wagon",
    "Bogzilla",
    "Braille Racer Twin Mill",
    "Buzz Kill",
    "Cadillac Project Hypercar",
    "Cadillac Project Hypercar O",
    "Chevroletor",
    "Chevy Blazer 4X4",
    "Toy Chevy Super Volt",
    "Chevy Super Volt",
    "Chill Mill",
    "Chill Mill Chill Mill",
    "Crescendo",
    "Crescendo O",
    "Cruise Bruiser",
    "Cupra E Racer",
    "Custom Ford Mustang",
    "Custom Cadillac",
    "Custom Chevy",
    "Custom Ford Truck",
    "Custom Ford Truck Custom Chevy Pickup",
    "Custom Ford Truck Custom Cadillac Fleetwood",
    "Custom Kia",
    "Czinger",
    "Datsun",
    "Decidedly Go",
    "Deora",
    "Disney Steamboat",
    "Delorean",
    "Delorean Dodge Van",
    "Draftnator",
    "Draggin Wagon",
    "Drift Ender",
    "Driftn Break",
    "Dune It Up",
    "El Segundo Rallye",
    "El Segundo Rallye O",
    "El Viento",
    "Feline Lucky",
    "Feline Lucky M",
    "Ferrari Competizione Red",
    "Ferrari Competizione Yellow",
    "Ferrari Competizione",
    "Ferrari Stradale",
    "Fiat 500E",
    "Fishd Chipd",
    "Flippin Fast",
    "Flippin Fast O",
    "Ford",
    "Ford Model Custom",
    "Ford Mustang Dark Horse",
    "Ford Mustang",
    "Jbb93 Ford Mustang",
    "Ford Performance Supervan",
    "Formula Gen3",
    "Futurismo",
    "Futurismo Gone Mad",
    "Gone Mad",
    "Gordon Murray Automotive",
    "Gordon Murray Automotive 50S",
    "Gordon Murray Automotive 50S Us",
    "Gotta Go",
    "Hako Type",
    "Hako Type High Tail Chaser",
    "Hirohata Merc",
    "Hi Roller",
    "Honda Cafe Turquoise",
    "Honda Civic Custom",
    "Honda Motocompo",
    "Honda Motocompo In Yellow",
    "Honda Motocompo In Yellow Hoto Roto",
    "Hoto Roto",
    "Hot Wheengs",
    "Concept",
    "Concept Formula Solar",
    "Concept Concept",
    "Ultimate Rex Transporter",
    "Ultimate Rex",
    "Jaguar",
    "Jaguar Coupe",
    "Kei Swap",
    "Kick Kart",
    "Kick Kart King Kuda",
    "Kowloond Hypervan",
    "Lamborghini Huracan Sterrato",
    "Lamborghini Huracan Sterrato Hot Wheels",
    "Lamborghini Huracan Sterrato Usa",
    "Lamborghini Huracan Sterrato Lamborghini Huracan Sterrato",
    "Lamborghini Huracan Sterrato Lamborghini Sian",
    "Land Rover Defender",
    "Later Crater",
    "Later Crater Layin Lowrider",
    "Layin Lowrider",
    "Layin Lowrider Lethal Diesel",
    "Lil Roar",
    "Limited Grip",
    "Bloc",
    "Bloc O",
    "Bloc Mailed It",
    "Maserati Shamal",
    "Mattel 80Th Anniversary Pack",
    "Mattel Dream Mobile",
    "Max Steel",
    "Mazda",
    "Mazda Autozam",
    "Mclaren Speedtail",
    "Collection Series Mcmurtry Speirling",
    "Mcmurtry Speirling",
    "Mercedes Petronas Formula One Team",
    "Mercedes Petronas Formula One Team Formula",
    "Mercedes Benz American",
    "Toy Mid Mill",
    "Mid Mill",
    "Mighty",
    "Minecart",
    "Mod Mill",
    "Monster Dairy Delivery",
    "Monteracer",
    "Morgan Super",
    "Mo Stash",
    "Muscle Bound",
    "Muscle Speeder",
    "Nerve Hammer",
    "Nissan Leaf",
    "Nissan Skyline",
    "Nissan Skyline Ollie Rocket",
    "Optimus Prime",
    "Oracle Red Bull Racing",
    "Pagani Utopia",
    "Peugeot Hypercar Hypervoiture",
    "Pixel Shaker",
    "Pixel Shaker O",
    "Polestar",
    "Polestar Pontiac Aztek Custom",
    "Pontiac Aztek Custom",
    "Porsche Carrera",
    "Porsche Carrera Clip",
    "Porsche Porsche Rallye",
    "Porsche Rallye",
    "Porsche Rallye Porsche",
    "Porsche Turbo Cabriolet",
    "Power Rocket",
    "Power Rocket Proton Saga",
    "Power Rocket Punk Rod",
    "Punk Rod",
    "Purple Passion",
    "Quick Bite",
    "Quick Bite Quick Bite",
    "Quick Chat",
    "Rally Speciale",
    "Range Rover Velar",
    "Rapid Pulse",
    "Renault Espace",
    "Renault Espace Rigor Motor",
    "Rodger Dodger",
    "Rrroadster",
    "Rrroadster Rrroadster",
    "Salt Shaker",
    "Shark Bite",
    "Silverado",
    "Silverado Silverado",
    "Skull Shaker",
    "Slide Burn",
    "Small Bloc",
    "Small Bloc Small Bloc",
    "Snoopy",
    "Snoopy Solar Reflex",
    "Snoopy Speed Driver",
    "Standard Kart",
    "Stockar",
    "Street Creeper",
    "Street Shrieker",
    "Subaru",
    "Subaru Impreza",
    "Supercharged",
    "Super Twin Mill",
    "Sushi Tuner",
    "Tesla Cyberquad",
    "Tesla Model Plaid",
    "Tesla Model Plaid Time Attaxi",
    "Toyota",
    "Toyota Supra",
    "Track Dwagon",
    "Track Dwagon Track Ripper",
    "Track Dwagon Triumph",
    "Series Batmobile",
    "Series Serie Tele Batmobile",
    "Twin Dorado",
    "The Vanster",
    "Vespa Super Sprint",
    "Vespa Super Sprint Vespa",
    "Volvo Drift Wagon",
    "Custom Wattzup",
    "Williams Racing",
    "Williams Racing Landspeeder",
    "Williams Racing Steam",
]

count = 0
for nome in nomes:
    if nome.strip():
        m = Miniatura(
            marca="",
            modelo=nome.strip(),
            preco=0,
            disponivel=True
        )
        m.save()
        count += 1

print(f"{count} miniaturas criadas com sucesso!")
