# Generated by Django 5.2.12 on 2026-03-29 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Miniatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca do Carro')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('ano', models.IntegerField(blank=True, null=True, verbose_name='Ano do Carro')),
                ('escala', models.CharField(choices=[('1:18', '1:18'), ('1:24', '1:24'), ('1:32', '1:32'), ('1:43', '1:43'), ('1:64', '1:64'), ('outro', 'Outro')], default='1:43', max_length=10, verbose_name='Escala')),
                ('fabricante', models.CharField(help_text='Ex: Bburago, Hot Wheels, Minichamps', max_length=100, verbose_name='Fabricante')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='miniaturas/', verbose_name='Foto')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço (R$)')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Miniatura',
                'verbose_name_plural': 'Miniaturas',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='Aquisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RESERVA', '🔖 Reserva'), ('RESERVA_PG', '💳 Reserva PG'), ('GARAGEM', '🏠 Garagem'), ('COLECAO', '🏆 Coleção')], default='RESERVA', max_length=20, verbose_name='Status')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('comprovante_pagamento', models.ImageField(blank=True, null=True, upload_to='comprovantes/', verbose_name='Comprovante de Pagamento')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aquisicoes', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('miniatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aquisicoes', to='garagem_app.miniatura', verbose_name='Miniatura')),
            ],
            options={
                'verbose_name': 'Aquisição',
                'verbose_name_plural': 'Aquisições',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfis/', verbose_name='Foto de Perfil')),
                ('bio', models.TextField(blank=True, verbose_name='Sobre')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
    ]
