# Generated by Django 5.2.12 on 2026-03-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniatura',
            name='escala',
            field=models.CharField(choices=[('1:18', '1:18'), ('1:24', '1:24'), ('1:32', '1:32'), ('1:43', '1:43'), ('1:64', '1:64'), ('outro', 'Outro')], default='1:64', max_length=10, verbose_name='Escala'),
        ),
        migrations.AlterField(
            model_name='miniatura',
            name='fabricante',
            field=models.CharField(blank=True, default='', help_text='Ex: Bburago, Hot Wheels, Minichamps', max_length=100, verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='miniatura',
            name='marca',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Marca do Carro'),
        ),
    ]
