# Generated by Django 5.2.12 on 2026-03-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem_app', '0002_alter_miniatura_escala_alter_miniatura_fabricante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquisicao',
            name='album',
            field=models.DateField(blank=True, null=True, verbose_name='Álbum'),
        ),
        migrations.AddField(
            model_name='miniatura',
            name='album',
            field=models.DateField(blank=True, null=True, verbose_name='Álbum'),
        ),
    ]
