# Generated by Django 5.2.12 on 2026-03-30 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem_app', '0003_aquisicao_album_miniatura_album'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aquisicao',
            name='album',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Álbum'),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data do Álbum')),
                ('status', models.CharField(choices=[('RESERVA', '🔖 Reserva'), ('RESERVA_PG', '💳 Reserva PG'), ('GARAGEM', '🏠 Garagem'), ('COLECAO', '🏆 Coleção')], default='RESERVA', max_length=20, verbose_name='Status')),
                ('pago', models.BooleanField(default=False, verbose_name='Pago (validado pelo admin)')),
                ('enviado', models.BooleanField(default=False, verbose_name='Enviado')),
                ('rastreio', models.CharField(blank=True, max_length=100, verbose_name='Código de Rastreio')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albuns', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Álbum',
                'verbose_name_plural': 'Álbuns',
                'ordering': ['-data'],
                'unique_together': {('cliente', 'data')},
            },
        ),
    ]
