# Generated by Django 5.2.8 on 2026-03-30 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garagem_app', '0004_alter_aquisicao_album_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aquisicao',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='aquisicao',
            name='miniatura',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Aquisicao',
        ),
        migrations.DeleteModel(
            name='Miniatura',
        ),
    ]
