# Generated by Django 5.2.8 on 2026-03-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem_app', '0006_alter_perfil_user_aquisição'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquisição',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='aquisicoes/', verbose_name='Foto da Miniatura'),
        ),
    ]
